# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(default=0, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=100, null=True)),
                ('participation_training', models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('core_join', models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('hear', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Alumni', 'Alumni'), ('Event', 'Event'), ('Instagram', 'Instagram'), ('Moringa-Website', 'Moringa-Website'), ('Referall', 'Referall'), ('Google', 'Google'), ('Nairobi-Tech-Week', 'Nairobi-Tech-Week'), ('Other', 'Other')], max_length=100, null=True)),
                ('influence', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Alumni', 'Alumni'), ('Event', 'Event'), ('Instagram', 'Instagram'), ('Moringa-Website', 'Moringa-Website'), ('Referall', 'Referall'), ('Google', 'Google'), ('Nairobi-Tech-Week', 'Nairobi-Tech-Week'), ('Other', 'Other')], max_length=100, null=True)),
                ('pay', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('education', models.CharField(choices=[('High-School', ''), ('Diploma', ''), ('Bachelor-Degree', 'Bachelor-Degree'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], max_length=100, null=True)),
                ('article_link', models.CharField(max_length=100)),
            ],
        ),
    ]
